settings:
  title: 'MPA Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)'

monitors:
  - id: api
    name: api.myponyasia.com
    description: 'A main API.'
    url: 'https://api.myponyasia.com/api'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: false

  - id: homebase
    name: myponyasia.com
    description: 'A homepage of MyPonyAsia.'
    url: 'https://myponyasia.com'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: true

  - id: pony
    name: pony.myponyasia.com
    description: 'A pony page of MyPonyAsia.'
    url: 'https://pony.myponyasia.com'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: true

  - id: anime
    name: anime.myponyasia.com
    description: 'A anime page of MyPonyAsia.'
    url: 'https://anime.myponyasia.com'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: true
