name = "mpastatus"
workers_dev = true
zone_id = ""
account_id = ""
route = ""
type = "webpack"
compatibility_date = "2021-11-06"

[build]
command = "yarn install && yarn build"

[build.upload]
format = "service-worker"

[triggers]
crons = ["* * * * *"]

# uncomment and adjust following if you are not using GitHub Actions
#[env.production]
#kv_namespaces = [{binding="KV_STATUS_PAGE", id="27582eac60b5415eae85e3aba4f719ee", preview_id="27582eac60b5415eae85e3aba4f719ee"}]
#zone_id="xxx"
#route="xxx"
